describe('Medical Notes',()=>{
    it('Doctor Save Note',()=>{
        cy.login()
        cy.patientTriage()
        cy.contains('Medical Encounter Note').click({force:true})
        cy.contains('General Practice').click().wait(1500)
        cy.contains('Proceed to Note').should('have.attr','disabled','disabled')
        cy.contains('Initial Visit').should('be.visible')
        cy.get('.entry-value').contains('Initial Visit').click()
        cy.contains('Proceed to Note').click()
        cy.contains('You are submitting an Encounter Note').should('be.visible')
        cy.contains('Discard').should('be.visible')
        cy.contains('Save as Draft').should('be.visible')
        cy.get('.form-buttons').contains('Submit').should('be.visible')
        // cy.contains('complaints').click()
        // cy.get('li').first().click()
        
        cy.contains('Save as Draft').click()
        cy.contains('RESUME').click()
        // cy.get('li').first().click()
        // cy.get('.form-buttons').contains('Submit').first().click({timeout:500})
        // cy.get('[name="heartRate"]').type('70')
        // cy.get('.form-buttons').contains('Submit').click()
    })
})


// describe('Medical Notes',()=>{
//     it('Doctor Discard Note',()=>{
//         cy.login()
//         cy.patientTriage()
//         cy.contains('Medical Encounter Note').click({force:true})
//         cy.contains('General Practice').click().wait(1500)
//         cy.contains('Proceed to Note').should('have.attr','disabled','disabled')
//         cy.contains('Initial Visit').should('be.visible')
//         cy.get('.entry-value').contains('Initial Visit').click()
//         cy.contains('Proceed to Note').click()
//         cy.contains('You are submitting an Encounter Note').should('be.visible')
//         cy.contains('Discard').should('be.visible')
//         cy.contains('Save as Draft').should('be.visible')
//         cy.get('.form-buttons').contains('Submit').should('be.visible')
        // cy.contains('complaints').click()
        // cy.get('li').first().click()
        
        // cy.contains('Discard').click()
        // cy.get('li').first().click()
        // cy.get('.form-buttons').contains('Submit').first().click({timeout:500})
        // cy.get('[name="heartRate"]').type('70')
        // cy.get('.form-buttons').contains('Submit').click()
//     })
// })