describe('Medical Notes',()=>{
    it('Doctor triage',()=>{
        cy.login()
        cy.patientTriage()
        cy.contains('Medical Encounter Note').click({force:true})
        cy.get('.EntryFormEncounter__form-selector-category').click().wait(1500)
        cy.contains('Proceed to Note').should('have.attr','disabled','disabled')
        cy.contains('Initial Visit').should('be.visible')
        cy.get('.entry-value').contains('Initial Visit').first().click()
        cy.contains('Proceed to Note').click()
        cy.contains('You are submitting an Encounter Note').should('be.visible')
        cy.contains('Discard').should('be.visible')
        cy.contains('Save as Draft').should('be.visible')
        cy.get('.form-buttons').contains('Submit').should('be.visible')
        cy.get(':nth-child(2) > form-component.ng-scope > .FormComponent > .row > .Grid-column-12 > .ng-scope > .LibraryDataMultiselectInfinite__container > .LibraryDataMultiselectInfinite__select > .LibraryDataMultiselectInfinite__search').click()
        cy.get(':nth-child(3) > .LibraryDataMultiselectInfinite__item').first().click()
        cy.get(':nth-child(36) > form-component.ng-scope > .FormComponent > .row > .Grid-column-12 > .ng-scope > .LibraryDataMultiselectInfinite__container > .LibraryDataMultiselectInfinite__select > .LibraryDataMultiselectInfinite__search').scrollIntoView()
        cy.get(':nth-child(36) > form-component.ng-scope > .FormComponent > .row > .Grid-column-12 > .ng-scope > .LibraryDataMultiselectInfinite__container > .LibraryDataMultiselectInfinite__select > .LibraryDataMultiselectInfinite__search').click()
        cy.get(':nth-child(3) > .LibraryDataMultiselectInfinite__item').first().click()
        cy.get('.form-buttons').contains('Submit').first().click({timeout:500})
        // cy.get('[name="heartRate"]').type('70')
        // cy.get('.form-buttons').contains('Submit').click()
    })
})